### ISSUE TITLE
Footer is displaying only on the last page

### ISSUE THREAD

**Issue by andoro** [BernhardBaumrock/RockPdf#2]
Dear @BernhardBaumrock ,

I tried to figure out myself without success, please help.

So I'm generating a huge PDF with around 37 pages, it's a pricelist of our categorized products.
This is the reason I'd like to output the page numbers and document title to the footer to every page.

I tried a lot of method, read the mPDF 7 docs etc. but none of the methods works for me.
The best version I could achieve is to have the footer on the last page.

My PDF generation code:

```php
<?php

// Get the pricelist
$priceList = renderPricelist($mainCats);

// RockPDF
$pdf = $this->modules->get('RockPdf');

$pdf->settings([
    'mode' => 'utf-8',
    'page_format' => 'A4',
    'defaultheaderline' => 0,
    'dpi' => 120,
    'img_dpi' => 300,
    'fontdata' => (new \Mpdf\Config\FontVariables())->getDefaults()['fontdata'] + [
            'DejaVuSansCondensed' => [
                'R' => 'DejaVuSansCondensed.ttf',
                'I' => 'DejaVuSansCondensed.ttf',
            ]
        ],
]);

// CSS styling
$less = $this->modules->get('RockLESS');
$css = $less->getCSS(__DIR__ . "/pricelistPDF.less")->css;
$pdf->write("<style>\n$css</style>");

$pdf->write('<div class="priceListPDF">'.$priceList.'</div>');

// Set footer
$footer ='<table width="100%" class="footer" name="myFooter">
        <tr>
            <td width="33%" style="font-family: DejaVuSansCondensed;">Szőlőskert Tüzép Árlista</td>
            <td width="33%" style="font-family: DejaVuSansCondensed; text-align: center;">{PAGENO}/{nbpg} oldal</td>
            <td width="33%" style="font-family: DejaVuSansCondensed; text-align: right;">{DATE Y-m-j}</td>
        </tr>
    </table>';

$pdf->set('SetFooter', $footer);

// Set META
$pdf->set('SetTitle', 'Szőlőskert Tüzép Árlista');
$pdf->set('SetAuthor', 'Földgép Transz Kft.');
$pdf->set('SetCreator', 'Földgép Transz Kft.');
$pdf->set('SetSubject', 'Szőlőskert Tüzép Árlista');
$pdf->set('SetKeywords', 'Szőlőskert Tüzép, Árlista');
//$pdf->set('SetProtection', array('copy', 'print', 'print-highres'));

// PDF output

//$pdf->write($footer);

$pdf->show();
?>
```

The CSS:

```css
/*@page {
  margin: 7mm 7mm 15mm 7mm; !* <any of the usual CSS values for margins> *!
  !*(% of page-box width for LR, of height for TB) *!
  margin-header: 0; !* <any of the usual CSS values for margins> *!
  margin-footer: 5mm; !* <any of the usual CSS values for margins> *!
  marks: none;!*crop | cross | none*!
  odd-footer-name: html_myFooter;
  even-footer-name: html_myFooter;
}*/

.priceListPDF {
  font-family: DejaVuSansCondensed;

  h1,h2,h3,h4,h5 {
    text-transform: uppercase;
  }

  table {
    border: 1px solid #000000;
    padding: 0;
    margin: 0;
  }

  tr:nth-child(even) {
    border-bottom: 0;
    background-color: #f2f2f2;
  }

  tr {
    //border: 1px;
  }

  th,td {
    border: 0.5px solid #000000;
    font-family: DejaVuSansCondensed;
    padding: 0.1cm;
    font-size: 12px;
  }

  a {
    text-decoration: none;
    color: black;
    white-space: nowrap;
  }
}
```

What am I doing wrong?
Why the footer is not generated automatically for every pages?
